#! /bin/bash

cd python

bold=$(tput bold)
dim=$(tput dim)
noformat=$(tput sgr0)

echo ""
echo "${dim}====================================================${noformat}"
echo " Creating and installing loom-viewer Python package"
echo "${dim}====================================================${noformat}"
echo ""


echo ""
echo "=== Removing previous Python build and dist folders (if any)"
echo ""

if [ -a ./build ]; then
  rm -rv ./build
fi
if [ -a ./dist ]; then
  rm -rv ./dist
fi

set -o nounset
set -o errexit
echo ""
echo "  Done"
echo ""

echo ""
echo "=== Creating and installing loom-viewer Python package"
echo ""

python setup.py install --force

echo ""
echo "  Done"
echo ""

cd ..