#! /bin/bash

echo ""
echo "==============================================="
echo " Removing previous Python build files (if any)"
echo "==============================================="
echo ""

if [ -a ./python/build ]; then
  echo " rm -r ./python/build"
  rm -r ./python/build
fi
if [ -a ./python/dist ]; then
  echo " rm -r ./python/dist"
  rm -r ./python/dist
fi

set -o nounset
set -o errexit
echo ""
echo "  Done"
echo ""

echo ""
echo ====================================================
echo " Creating and installing loom-viewer Python package"
echo ====================================================
echo ""

# I haven't figured out how to both generate correct paths in the webpack HTML
# template, and have the resulting index.html be put in the right folders.
# Yes, this is an ugly hack around my incompetence, but it works - Job
mv ./python/loom_viewer/index.html ./python/loom_viewer/static/index.html
cp ./client/images/favicon.ico ./python/loom_viewer/static/favicon.ico
cd python
python setup.py install --force
cd ..
