#! /bin/bash

bold=$(tput bold)
dim=$(tput dim)
noformat=$(tput sgr0)

echo ""
echo "${dim}=================================================${noformat}"
echo " Removing previous WebPack build files (if any)"
echo "${dim}=================================================${noformat}"
echo ""

# Remove old files
if [ -a ./python/loom_viewer/static/ ]; then
  echo " rm -r ./python/loom_viewer/static/"
  rm -r ./python/loom_viewer/static/
fi

set -o nounset
set -o errexit
echo ""
echo "  Done"
echo ""

# Build static assets

echo ""
if  [ "${1:-dev}" == "dev" ]; then
  echo "${dim}================================================================${noformat}"
  echo " Bundling development build and inserting it into HTML template"
  echo "${dim}================================================================${noformat}"
  echo ""

  webpack --config='webpack.config.dev.js' --progress --profile --colors

  echo ""
  echo "  Done"
  echo ""  

elif [ "${1:-dev}" == "prod" ]; then
  echo "${dim}==========================================================${noformat}"
  echo " Building for production. Minifying + bundling production"
  echo "         build and inserting it into HTML template"
  echo "${dim}==========================================================${noformat}"
  echo ""

  webpack --config='webpack.config.prod.js' --progress --profile --colors

  echo ""
  echo "  Done"
  echo ""

else
  echo " ${bold}ERROR: Incorrect flags passed for WebPack build${noformat}"
  echo ""
  exit 1
fi