#! /bin/bash

bold=$(tput bold)
dim=$(tput dim)
noformat=$(tput sgr0)

echo ""
echo "${dim}====================================${noformat}"
echo " Building Client Web App (WebPack)"
echo "${dim}====================================${noformat}"


echo ""
echo "=== Removing previous client build files (if any)"
echo ""

# Remove old files
if [ -a ./python/loom_viewer/static/ ]; then
  rm -rv ./python/loom_viewer/static/
fi

set -o nounset
set -o errexit
echo ""
echo "  Done"
echo ""

# Build static assets

echo ""
if  [ "${1:-dev}" == "dev" ]; then
  echo "=== Run WebPack with development build"
  echo ""

  webpack --config='webpack.config.dev.js' --progress --profile --colors

  # I haven't figured out how to both generate correct paths in the webpack HTML
  # template, and have the resulting index.html be put in the right folders.
  # Yes, this is an ugly hack around my incompetence, but it works - Job
  mv ./python/loom_viewer/index.html ./python/loom_viewer/static/index.html
  cp ./client/images/favicon.ico ./python/loom_viewer/static/favicon.ico

  echo ""
  echo "  Done"
  echo ""

elif [ "${1:-dev}" == "prod" ]; then
  echo "=== Run WebPack with production build"
  echo ""

  webpack --config='webpack.config.prod.js' --progress --profile --colors

  mv ./python/loom_viewer/index.html ./python/loom_viewer/static/index.html
  cp ./client/images/favicon.ico ./python/loom_viewer/static/favicon.ico

  echo ""
  echo "  Done"
  echo ""

else
  echo " ${bold}ERROR: Incorrect flags passed for WebPack build${noformat}"
  echo ""
  exit 1
fi