#! /bin/bash

bold=$(tput bold)
dim=$(tput dim)
noformat=$(tput sgr0)

echo ""
echo "${dim}====================================================${noformat}"
echo " Creating and installing loom-viewer Python package"
echo "${dim}====================================================${noformat}"
echo ""


echo ""
echo "=== Removing previous Python build files (if any)"
echo ""

if [ -a ./python/build ]; then
  rm -rv ./python/build
fi
if [ -a ./python/dist ]; then
  rm -rv ./python/dist
fi

set -o nounset
set -o errexit
echo ""
echo "  Done"
echo ""

echo ""
echo "=== Creating and installing loom-viewer Python package"
echo ""

cd python
python setup.py install --force
cd ..

echo ""
echo "  Done"
echo ""