#! /bin/bash
if [ -a ./python/static/js ]; then
  rm -r ./python/static/js
fi
set -o nounset
set -o errexit

# Set up the static directory
mkdir ./python/static/js

# Build all the static assets
echo "Building static assets."
BINPATH=$(npm -g bin)
echo "Bundling CSS"
$BINPATH/uglifycss ./client/css/* > ./python/static/css/bundle.min.css

echo "Minifying JS bundle"
webpack
# I can't figure out how to both generate correct paths in the HTML template
# of webpack, and have the resulting index.html be put in the right folders.
# Yes, it's an ugly hack, but it works - Job
mv python/index.html python/static/index.html
