#! /bin/bash

# Remove old files
if [ -a ./python/loompy/static/js ]; then
  rm -r ./python/loompy/static/js
fi
if [ -a ./python/loompy/static/css ]; then
  rm -r ./python/loompy/static/css
fi
if [ -a ./python/build ]; then
  rm -r ./python/build
fi
if [ -a ./python/dist ]; then
  rm -r ./python/dist
fi

set -o nounset
set -o errexit

# Set up the static directory
mkdir ./python/loompy/static/js
mkdir ./python/loompy/static/css

# Build static assets

if  [ "${1:-dev}" == "dev" ]; then
  echo "Bundling development build and inserting it into HTML template"
  webpack --config='webpack.config.dev.js' --progress --profile --colors
else
  echo "Minifying + bundling production build and inserting it into HTML template"
  webpack --config='webpack.config.prod.js' --progress --profile --colors
fi

echo "Building static assets."
uglifycss ./client/css/* > ./python/loompy/static/css/bundle.min.css
# I can't figure out how to both generate correct paths in the HTML template
# of webpack, and have the resulting index.html be put in the right folders.
# Yes, it's an ugly hack, but it works - Job
mv ./python/loompy/index.html ./python/loompy/static/index.html
cp -R ./client/fonts ./python/loompy/static/
cd python
echo "Installing loom python package"
python setup.py install --force
cd ..