#! /bin/bash

gcloud compute ssh loom --command "sudo /home/Sten/anaconda2/bin/supervisorctl stop all"
rm ./python/*.pyc 2> /dev/null # Needed to prevent access denied errors
gcloud compute copy-files python/ root@loom:/srv/loom/
gcloud compute ssh loom --command "sudo /home/Sten/anaconda2/bin/supervisorctl start all"
