#! /bin/bash

#Check for any MySQL settings passed as flags
while test $# -gt 0; do
        case "$1" in
                --help)
                        echo "-u, --user=MYSQL_USERNAME"
                        echo "-h, --host=MYSQL_HOST"
                        echo "-p, --port=MYSQL_PORT"
                        exit 0
                        ;;
                -u)
                        shift
                        if test $# -gt 0; then
                                export MYSQL_USERNAME=$1
                        else
                                echo "no MYSQL_USER specified"
                                exit 1
                        fi
                        shift
                        ;;
                --user*)
                        export MYSQL_USERNAME=`echo $1 | sed -e 's/^[^=]*=//g'`
                        shift
                        ;;
                -p)
                        shift
                        if test $# -gt 0; then
                                export MYSQL_PORT=$1
                        else
                                echo "no MYSQL_PORT specified"
                                exit 1
                        fi
                        shift
                        ;;
                --port*)
                        export MYSQL_PORT=`echo $1 | sed -e 's/^[^=]*=//g'`
                        shift
                        ;;
                -h)
                        shift
                        if test $# -gt 0; then
                                export MYSQL_HOST=$1
                        else
                                echo "no MYSQL_HOST specified"
                                exit 1
                        fi
                        shift
                        ;;
                --host*)
                        export MYSQL_HOST=`echo $1 | sed -e 's/^[^=]*=//g'`
                        shift
                        ;;

                *)
                        break
                        ;;
        esac
done

#prompt user for missing variables
if [ -z ${MYSQL_USERNAME+x} ]; then
  read -p "Enter MySQL user: " export MYSQL_USERNAME
fi
if [ -z ${MYSQL_HOST+x} ]; then
  read -p "Enter MySQL host: " export MYSQL_HOST
fi
if [ -z ${MYSQL_PORT+x} ]; then
  read -p "Enter MySQL port: " export MYSQL_PORT
fi

#prompt user for password
read -s -p "Enter MYSQL_PASSWORD: " t
export MYSQL_PASSWORD=$t
echo ''

./release/loom
#echo "Moving the static folder to inside the python folder"
#echo "Feel free to delete it when you're done"
#if [ -a ./static ]; then
#    mv ./static/ ./python/
#fi
#sudo -E python python/loom_server.py 

