export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const REQUEST_PROJECTS_FAILED = 'REQUEST_PROJECTS_FAILED';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const SEARCH_PROJECTS = 'SEARCH_PROJECTS';

export const REQUEST_DATASET = 'REQUEST_DATASET';
export const REQUEST_DATASET_CACHED = 'REQUEST_DATASET_CACHED';
export const REQUEST_DATASET_FAILED = 'REQUEST_DATASET_FAILED';
export const RECEIVE_DATASET = 'RECEIVE_DATASET';

export const REQUEST_GENE = 'REQUEST_GENE';
export const REQUEST_GENE_FAILED = 'REQUEST_GENE_FAILED';
export const RECEIVE_GENE = 'RECEIVE_GENE';

export const SET_HEATMAP_PROPS = 'SET_HEATMAP_PROPS';
export const SET_GENESCAPE_PROPS = 'SET_GENESCAPE_PROPS';
export const SET_LANDSCAPE_PROPS = 'SET_LANDSCAPE_PROPS';
export const SET_SPARKLINE_PROPS = 'SET_SPARKLINE_PROPS';
export const SET_VIEW_PROPS = 'SET_VIEW_PROPS';