export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const REQUEST_PROJECTS_FAILED = 'REQUEST_PROJECTS_FAILED';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';

export const REQUEST_DATASET = 'REQUEST_DATASET';
export const REQUEST_DATASET_FAILED = 'REQUEST_DATASET_FAILED';
export const RECEIVE_DATASET = 'RECEIVE_DATASET';

export const REQUEST_GENE = 'REQUEST_GENE';
export const REQUEST_GENE_FAILED = 'REQUEST_GENE_FAILED';
export const RECEIVE_GENE = 'RECEIVE_GENE';